version: '3.8'

services:
  my_service:
    image: zenitbrain
    networks:
      my_custom_network:
        ipv4_address: 192.168.123.101

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.123.0/24